version: 2.1

orbs:
  node: circleci/node@3.0.1

jobs:
  build:
    working_directory: ~/one-piece-location
    executor: node/default
    steps:
      - checkout
      - node/install-npm 
      - node/install-packages:
          app-dir: ~/one-piece-location
          cache-path: node_modules
          override-ci-command: sudo npm i
      - persist_to_workspace:
          root: .
          paths:
            - .

  test:
    docker:
      - image: kartoza/postgis:13.0
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 123
          POSTGRES_DB: onepiece-test
      - image: redis:alpine
      - image: "rabbitmq:3-management"
        environment:
          RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
          RABBITMQ_DEFAULT_USER: "rabbitmq"
          RABBITMQ_DEFAULT_PASS: "rabbitmq"
          RABBITMQ_DEFAULT_VHOST: "/"
      - image: cimg/node:current
        environment:
          REDIS_URL: tcp://localhost:6379
    steps:
      - attach_workspace:
          at: .
      - run:
          name: build
          command: npm run build
      - run:
          name: Test
          command: npm run test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build